webServerPort: 3000
renderServerPort: 4000
serverAddress: "http://localhost"
urlShortenerAddress: "https://openapi.naver.com/v1/util/shorturl"
naverClientId: "GIdHFmiMjp1MlgWQ80VL"
naverClientSecret: "tQy57uaafh"
