webServerPort: 3000
renderServerAddress: "http://localhost:4000"
urlShortenerAddress: "https://openapi.naver.com/v1/util/shorturl"
naverClientId: "GIdHFmiMjp1MlgWQ80VL"
naverClientSecret: "tQy57uaafh"